In [2]:
import numpy as np
import pandas as pd
from kmodes.kmodes import KModes


In [3]:
data = np.random.choice(20, (100, 10))

In [4]:
data

array([[18,  3, 14, 17,  9,  7,  2,  1, 14, 18],
       [ 9,  0, 19, 13,  4,  6,  6, 11, 13, 18],
       [17, 12,  2,  8,  6, 10,  8,  4, 15,  5],
       [ 8,  9,  1,  3, 19,  9, 19, 17,  7,  0],
       [12,  5,  7,  5,  6, 12,  4, 12,  8,  4],
       [10,  2, 15,  5,  8, 17,  7, 10,  5, 19],
       [ 0,  3, 11,  4,  8, 13,  1,  9, 12, 19],
       [18,  9, 19, 11, 17, 14, 14,  6, 18,  1],
       [12, 18, 14,  9,  7,  8,  3, 11,  7,  9],
       [17,  2, 11, 15,  0,  6, 19,  1,  9,  9],
       [ 7,  6, 13,  6, 14, 14,  3,  7,  3,  6],
       [13, 11, 16,  8, 14,  5, 17, 12,  1,  1],
       [18,  8,  7,  1,  1,  0, 16,  3,  6, 11],
       [16, 11,  5, 13,  1,  4,  5, 13, 13,  7],
       [ 7,  0,  4, 14,  4, 11, 14, 16,  8,  8],
       [11, 15,  6,  4, 14,  0, 10,  7,  4,  7],
       [18, 13,  1, 13, 17,  3, 15, 11, 15,  9],
       [ 7,  0,  8,  8,  8, 19, 18,  1,  2,  5],
       [ 1, 12,  5,  8, 12, 19,  3, 10,  2, 18],
       [ 5, 10,  4,  9,  6,  4, 13,  0, 18,  7],
       [11,  0,  4, 

In [5]:
dataset = pd.DataFrame({'a': data[:, 0], 'b': data[:, 1], 'c': data[:, 2], 'd': data[:, 3], 'e': data[:, 4], 'f': data[:, 5], 'g': data[:, 6], 'h': data[:, 7], 'i': data[:, 8], 'j': data[:, 9]})

In [6]:
dataset

a   b   c   d   e   f   g   h   i   j
0   18   3  14  17   9   7   2   1  14  18
1    9   0  19  13   4   6   6  11  13  18
2   17  12   2   8   6  10   8   4  15   5
3    8   9   1   3  19   9  19  17   7   0
4   12   5   7   5   6  12   4  12   8   4
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
95   4  12   5   8  16  14   1   7   7   7
96   4  19  12   8   8  16   9  17   3   6
97   1   3  14  11   8  12  16   1   0   2
98  10  17   0   0   4   5   1   6   1  12
99  18  14   9  14  11   6  13  13  14   9

[100 rows x 10 columns]

In [24]:
km = KModes(n_clusters=3, init='Huang', n_init=5, verbose=1)

In [26]:
clusters = km.fit_predict(data)


Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 18, cost: 822.0
Run 1, iteration: 2/100, moves: 8, cost: 819.0
Run 1, iteration: 3/100, moves: 1, cost: 819.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 23, cost: 830.0
Run 2, iteration: 2/100, moves: 1, cost: 830.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 19, cost: 823.0
Run 3, iteration: 2/100, moves: 0, cost: 823.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 15, cost: 824.0
Run 4, iteration: 2/100, moves: 3, cost: 824.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 14, cost: 829.0
Run 5, iteration: 2/100, moves: 6, cost: 829.0
Best run was number 1


In [28]:
kmodes = km.cluster_centroids_
shape = kmodes.shape

In [32]:
print(kmodes)

[[ 8  1  2  0  3  8  6 19  9  4]
 [ 6  4 19 14  0  0 12  6  5  5]
 [15  2 13  6 18  7  0  4 14  0]]


In [29]:
for i in range(shape[0]):
    if sum(kmodes[i,:]) == 0:
        print("\ncluster " + str(i) + ": ")
        print("no-skills cluster")
    else:
        print("\ncluster " + str(i) + ": ")
        cent = kmodes[i,:]
        for j in dataset.columns[np.nonzero(cent)]:
            print(j)


cluster 0: 
a
b
c
e
f
g
h
i
j

cluster 1: 
a
b
c
d
g
h
i
j

cluster 2: 
a
b
c
d
e
f
h
i


In [18]:
km

KModes(cat_dissim=<function matching_dissim at 0x7f1b66d27dd0>, init='Huang',
       max_iter=100, n_clusters=3, n_init=5, n_jobs=1, random_state=None,
       verbose=1)

In [ ]:
km.